# Generated by Django 4.2.24 on 2025-09-10 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='系统自动生成的唯一标识符', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建的UTC时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新的UTC时间', verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=20, verbose_name='状态')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
                'db_table': 'persons_person',
                'indexes': [models.Index(fields=['status'], name='idx_person_status')],
            },
        ),
    ]
