# Generated by Django 4.2.24 on 2025-09-10 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='系统自动生成的唯一标识符', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建的UTC时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新的UTC时间', verbose_name='更新时间')),
                ('role', models.CharField(choices=[('teacher', '教师'), ('researcher', '教研'), ('operator', '运营')], max_length=20, verbose_name='角色')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='persons.person', verbose_name='人员')),
            ],
            options={
                'verbose_name': '人员角色',
                'verbose_name_plural': '人员角色',
                'db_table': 'persons_person_role',
                'indexes': [models.Index(fields=['person'], name='idx_personrole_person'), models.Index(fields=['role'], name='idx_personrole_role')],
            },
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.UniqueConstraint(fields=('person', 'role'), name='uq_person_role'),
        ),
    ]
