# Generated by Django 4.2.24 on 2025-09-11 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_personrole_personrole_uq_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='系统自动生成的唯一标识符', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建的UTC时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新的UTC时间', verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='软删除标记时间，为空表示未删除', null=True, verbose_name='删除时间')),
                ('type', models.CharField(choices=[('injury_notice', '学员伤病'), ('teaching_reminder', '教学提醒')], max_length=64, verbose_name='公告类型')),
                ('content', models.TextField(help_text='公告内容文本（可扩展为富文本存储或富文本渲染）', verbose_name='公告内容')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, help_text='公告开始生效时间（UTC）', verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, help_text='公告结束时间（UTC），为空视为仍有效', null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='persons.person', verbose_name='创建者')),
                ('publisher', models.ForeignKey(help_text='发布公告的人员（教研）', on_delete=django.db.models.deletion.PROTECT, related_name='published_announcements', to='persons.person', verbose_name='发布人')),
                ('updated_by', models.ForeignKey(blank=True, help_text='最后更新此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='persons.person', verbose_name='更新者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcements_announcement',
                'indexes': [models.Index(fields=['type'], name='idx_ann_type'), models.Index(fields=['publisher'], name='idx_ann_publisher'), models.Index(fields=['start_at', 'end_at'], name='idx_ann_window')],
            },
        ),
    ]
