# Generated by Django 4.2.24 on 2025-09-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='e2e_type',
            field=models.CharField(choices=[('T2R', 'T→R'), ('T2O', 'T→O'), ('R2T', 'R→T'), ('R2O', 'R→O'), ('O2T', 'O→T'), ('O2R', 'O→R'), ('O2O', 'O→O')], help_text='系统根据发送人与接收人角色自动推断（T→R/T→O/R→T/R→O/O→T/O→R/O→O）', max_length=8, verbose_name='端到端类别'),
        ),
    ]
