# Generated by Django 4.2.24 on 2025-09-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_e2e_type'),
        ('evaluations', '0005_studentpiecestatus_and_more'),
    ]

    operations = [
        # Drop the existing foreign key constraint
        migrations.RunSQL(
            "ALTER TABLE reminders_reminder DROP CONSTRAINT IF EXISTS notifications_remind_feedback_id_b97273b2_fk_evaluatio;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        # Recreate the foreign key constraint with SET NULL
        migrations.RunSQL(
            "ALTER TABLE reminders_reminder ADD CONSTRAINT reminders_reminder_feedback_id_fk FOREIGN KEY (feedback_id) REFERENCES evaluations_feedback_record(id) ON DELETE SET NULL;",
            reverse_sql="ALTER TABLE reminders_reminder DROP CONSTRAINT IF EXISTS reminders_reminder_feedback_id_fk;"
        ),
    ]
