# Generated by Django 4.2.24 on 2025-09-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_auto_20250916_0224'),
    ]

    operations = [
        # Drop the remaining problematic constraints
        migrations.RunSQL(
            "ALTER TABLE reminders_reminder DROP CONSTRAINT IF EXISTS notifications_remind_feedback_id_b97273b2_fk_evaluatio;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "ALTER TABLE reminders_reminder DROP CONSTRAINT IF EXISTS reminders_reminder_feedback_id_a42390bf_fk_evaluatio;",
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]
