# Generated by Django 4.2.24 on 2025-09-10 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_personrole_personrole_uq_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='系统自动生成的唯一标识符', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建的UTC时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新的UTC时间', verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签名')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '学员标签',
                'verbose_name_plural': '学员标签',
                'db_table': 'students_student_tag',
                'indexes': [models.Index(fields=['name'], name='idx_studenttag_name')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='系统自动生成的唯一标识符', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建的UTC时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新的UTC时间', verbose_name='更新时间')),
                ('xiaoetong_id', models.CharField(max_length=64, unique=True, verbose_name='小鹅通ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('remark_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注名')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=20, verbose_name='状态')),
                ('teacher_impression_current', models.TextField(blank=True, null=True, verbose_name='教师印象（当前）')),
                ('op_note', models.TextField(blank=True, null=True, verbose_name='运营备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_created', to='persons.person', verbose_name='创建者')),
                ('tags', models.ManyToManyField(blank=True, related_name='students', to='students.studenttag', verbose_name='标签')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_updated', to='persons.person', verbose_name='更新者')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'db_table': 'students_student',
                'indexes': [models.Index(fields=['xiaoetong_id'], name='idx_student_xiaoetong'), models.Index(fields=['nickname'], name='idx_student_nickname'), models.Index(fields=['status'], name='idx_student_status')],
            },
        ),
    ]
