# Generated by Django 4.2.24 on 2025-09-10 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_personrole_personrole_uq_person_role'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='系统自动生成的唯一标识符', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建的UTC时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新的UTC时间', verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='软删除标记时间，为空表示未删除', null=True, verbose_name='删除时间')),
                ('course_status', models.CharField(choices=[('not_started', '未开始'), ('learning', '学习中'), ('finished', '已学完'), ('paused', '暂停'), ('transferred', '转课')], default='not_started', max_length=20, verbose_name='课程学习状态')),
                ('record_status', models.CharField(choices=[('active', '有效'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='记录状态')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_records', to='courses.course', verbose_name='课程')),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_records', to='courses.courseversion', verbose_name='课程版本')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='persons.person', verbose_name='创建者')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_records', to='students.student', verbose_name='学员')),
                ('updated_by', models.ForeignKey(blank=True, help_text='最后更新此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='persons.person', verbose_name='更新者')),
            ],
            options={
                'verbose_name': '学员课程记录',
                'verbose_name_plural': '学员课程记录',
                'db_table': 'students_course_record',
                'indexes': [models.Index(fields=['student'], name='idx_cr_student'), models.Index(fields=['course'], name='idx_cr_course'), models.Index(fields=['course_version'], name='idx_cr_course_ver'), models.Index(fields=['record_status'], name='idx_cr_status'), models.Index(fields=['start_at', 'end_at'], name='idx_cr_period')],
            },
        ),
    ]
