# Generated by Django 4.2.24 on 2025-09-11 02:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_courserecord'),
        ('persons', '0002_personrole_personrole_uq_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='系统自动生成的唯一标识符', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建的UTC时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新的UTC时间', verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='软删除标记时间，为空表示未删除', null=True, verbose_name='删除时间')),
                ('seq_no', models.PositiveIntegerField(verbose_name='回访序号')),
                ('status', models.CharField(choices=[('pending', '未处理'), ('done', '已处理'), ('closed', '关闭')], default='pending', max_length=20, verbose_name='回访状态')),
                ('purpose', models.CharField(choices=[('regular', '常规回访'), ('issue_tracking', '问题跟进'), ('renewal_reminder', '续费提醒'), ('complaint_handling', '投诉处理'), ('other', '其他')], default='regular', max_length=50, verbose_name='回访目的')),
                ('urgency', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='紧急度')),
                ('content', models.TextField(verbose_name='回访内容')),
                ('result', models.TextField(blank=True, null=True, verbose_name='回访结果')),
                ('need_follow_up', models.BooleanField(default=False, verbose_name='是否需要跟进')),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True, verbose_name='下次回访计划时间')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='persons.person', verbose_name='创建者')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operated_follow_ups', to='persons.person', verbose_name='回访人员')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_records', to='students.student', verbose_name='学员')),
                ('updated_by', models.ForeignKey(blank=True, help_text='最后更新此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='persons.person', verbose_name='更新者')),
            ],
            options={
                'verbose_name': '回访记录',
                'verbose_name_plural': '回访记录',
                'db_table': 'followups_followup_record',
                'indexes': [models.Index(fields=['student'], name='idx_fup_student'), models.Index(fields=['operator'], name='idx_fup_operator'), models.Index(fields=['status'], name='idx_fup_status'), models.Index(fields=['urgency'], name='idx_fup_urgency'), models.Index(fields=['created_at'], name='idx_fup_created')],
            },
        ),
        migrations.AddConstraint(
            model_name='followuprecord',
            constraint=models.UniqueConstraint(fields=('student', 'seq_no'), name='uq_fup_seq'),
        ),
    ]
