# Generated by Django 4.2.24 on 2025-09-11 02:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_courserecord'),
        ('courses', '0001_initial'),
        ('persons', '0002_personrole_personrole_uq_person_role'),
        ('evaluations', '0004_finalize_piece_drop_piece_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPieceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='系统自动生成的唯一标识符', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建的UTC时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新的UTC时间', verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='软删除标记时间，为空表示未删除', null=True, verbose_name='删除时间')),
                ('review_count', models.PositiveIntegerField(default=0, help_text='累计被点评的总次数（随每次点评递增）', verbose_name='被点评次数')),
                ('last_reviewed_at', models.DateTimeField(blank=True, help_text='最近一次被点评的UTC时间', null=True, verbose_name='最后点评时间')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='persons.person', verbose_name='创建者')),
                ('last_feedback', models.ForeignKey(blank=True, help_text='最近一次更新本状态的点评记录，允许为空以兼容点评记录被删除', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_piece_statuses', to='evaluations.feedbackrecord', verbose_name='关联点评记录')),
                ('piece', models.ForeignKey(help_text='状态所属的曲目', on_delete=django.db.models.deletion.PROTECT, related_name='student_statuses', to='courses.piece', verbose_name='曲目')),
                ('student', models.ForeignKey(help_text='状态所属的学员', on_delete=django.db.models.deletion.PROTECT, related_name='piece_statuses', to='students.student', verbose_name='学员')),
                ('updated_by', models.ForeignKey(blank=True, help_text='最后更新此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='persons.person', verbose_name='更新者')),
            ],
            options={
                'verbose_name': '学员曲目状态',
                'verbose_name_plural': '学员曲目状态',
                'db_table': 'evaluations_student_piece_status',
                'indexes': [models.Index(fields=['student'], name='idx_sps_student'), models.Index(fields=['piece'], name='idx_sps_piece'), models.Index(fields=['last_reviewed_at'], name='idx_sps_last_reviewed'), models.Index(fields=['review_count'], name='idx_sps_review_count')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentpiecestatus',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('student', 'piece'), name='uq_sps_student_piece_not_deleted'),
        ),
    ]
