# Generated by Django 4.2.24 on 2025-09-11 02:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_personrole_personrole_uq_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='系统自动生成的唯一标识符', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建的UTC时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新的UTC时间', verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='软删除标记时间，为空表示未删除', null=True, verbose_name='删除时间')),
                ('type', models.CharField(choices=[('task_assigned', '任务分配'), ('task_completed', '任务完成'), ('reminder_received', '收到提醒'), ('follow_up_todo', '回访待办'), ('announcement_published', '公告发布')], max_length=50, verbose_name='通知类型')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('link_type', models.CharField(blank=True, choices=[('evaluation_task', '点评任务'), ('feedback_record', '点评记录'), ('reminder', '提醒事项'), ('announcement', '公告'), ('follow_up', '回访记录'), ('student', '学员')], max_length=50, null=True, verbose_name='关联对象类型')),
                ('link_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='persons.person', verbose_name='创建者')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='persons.person', verbose_name='接收人')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='persons.person', verbose_name='发送人')),
                ('updated_by', models.ForeignKey(blank=True, help_text='最后更新此记录的人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='persons.person', verbose_name='更新者')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'db_table': 'notifications_notification',
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='idx_ntf_recipient_read'), models.Index(fields=['recipient', 'created_at'], name='idx_ntf_recipient_created'), models.Index(fields=['type'], name='idx_ntf_type'), models.Index(fields=['link_type', 'link_id'], name='idx_ntf_link')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('link_id__isnull', True), ('link_type__isnull', True)), models.Q(('link_id__isnull', False), ('link_type__isnull', False)), _connector='OR'), name='ck_notif_link_pair_coherence'),
        ),
    ]
