# Generated by Django 4.2.24 on 2025-09-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # Drop the problematic foreign key constraint from notifications_reminder table
        migrations.RunSQL(
            "ALTER TABLE notifications_reminder DROP CONSTRAINT IF EXISTS notifications_remind_feedback_id_b97273b2_fk_evaluatio;",
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]
